version: "3.9"
services:
  db:
    container_name: db_rails
    image: postgres:14.1-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432
    env_file: .env
  web_rails:
    container_name: web_rails
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8888 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "8888:8888"
    depends_on:
      - db
  meilisearch_rails:
    container_name: meilisearch_rails
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    volumes:
      - meilisearch:/var/lib/meilisearch/data
  adminer_rails:
    container_name: adminer_rails
    image: adminer
    ports:
      - 5555:8080
    environment:
      - ADMINER_DESIGN=mvt
    logging:
      driver: "none"
volumes:
  postgres:
  meilisearch: